# Generated by Django 3.1.3 on 2022-05-18 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20220504_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='modity_date',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modity_date',
            new_name='modify_date',
        ),
    ]
